BCMS/BCMS/Models/Report.cs
using BCMS.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Security;


namespace BlueConsultingManagementSystem.Models
{
    public class Report
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ReportPK { get; set; }

        [Required]
        public string ReportName { get; set; }

        //[Required]
        public string ConsultantName { get; set; }

        [Required]
        public DepartmentType type { get; set; }

        public string SupervisorName { get; set; }

        //This is the name of the supervisor. fix later
        //[Required]
        public string SupervisorApproved { get; set; }

        //[Required]
        public string StaffApproval { get; set; }

        //[Required]
        public DateTime? DateOfApproval { get; set; }

        public virtual List<Expense> Expenses { get; set; }

        public virtual Report Parent { get; set; }

        [InverseProperty("Parent")]
        public virtual List<Report> Children { get; set; }

        [NotMapped]
        public string FullReport
        {
            get
            {
                return ReportName + " " + ConsultantName + " " + type + " " + SupervisorApproved + " " + SupervisorApproved + " " + StaffApproval + " " + DateOfApproval;
            }
        }

        public virtual void SetConsultantName(string name)
        {
            ConsultantName = name; 
        }

        public virtual void SetSupervisorName(string name)
        {
            SupervisorName = name;
        }

        public virtual void SetSupervisorStatusToSubmitted()
        {
            SupervisorApproved = "Submitted";
        }

        public virtual void SetSupervisorStatusToRejected()
        {
            SupervisorApproved = "Rejected";
        }

        public virtual void SetSupervisorStatusToApproved()
        {
            SupervisorApproved = "Approved";
        }

        public virtual void SetStaffStatusToRejected()
        {
            StaffApproval = "Rejected";
        }

        public virtual void SetStaffStatusToApproved()
        {
            StaffApproval = "Approved";
        }

        public virtual void SetDateOfApproval()
        {
            DateOfApproval = DateTime.Now.Date;
        }

        //[NotMapped]
        //public List<Report> GenerateSupervisorReportList()
        //{
        //    List<Report> reports = new List<Report>();

        //    foreach(Report rp in Report)

        //    return reports;
        //}
    }
}

BCMS/BCMS/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlueConsultingManagementSystem.Models;
using BCMS.Models;

namespace BCMS.Controllers
{
    public class ExpenseController : Controller
    {
        private BCMSContext db;

        public ExpenseController()
        {
            db = new BCMSContext();
        }

        // GET: /Expense/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var expense = db.Expenses.Include(x => x.Report).Where(x => x.ExpensePK == id).Single();
            if (expense == null)
            {
                return HttpNotFound();
            }

            return View(expense);
        }

        // GET: /Expense/Create
        public ActionResult Create(int ReportID)
        {
            ViewBag.ReportName = db.Reports.Find(ReportID).ReportName;
            //Saves the session to be used between page navigation
            if (Session["ReportID"] == null)
            {
                Session["ReportID"] = ReportID;                
            }
            return View();
        }
 
        // POST: /Expense/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExpensePK,Description,Location,Amount,CType,DateOfExpense")] Expense expense, HttpPostedFileBase PdfUpload )
        {
            if (ModelState.IsValid)
            {
                //Adds a PDF to the expense if the supplied PDF value is not null...
                if (PdfUpload != null)
                {
                     string filetype = PdfUpload.ContentType;
                     expense.PDFFile = new byte[PdfUpload.ContentLength];
                     PdfUpload.InputStream.Read(expense.PDFFile, 0, PdfUpload.ContentLength);
                }
                //Otherwise it creates it without one
                expense.Report = db.Reports.Find(Session["ReportID"]);
                db.Expenses.Add(expense);
                db.SaveChanges();
                Report report = db.Reports.Find(Session["ReportID"]);               
                return RedirectToAction("../Report/Details/" + Session["ReportID"]);              
            }
            return RedirectToAction("index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public FileContentResult PDFView(int? id)
        {
            return File(db.Expenses.Find(id).PDFFile, "application/pdf");
        }
    }
}

BCMS/BCMS/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlueConsultingManagementSystem.Models;
using BCMS.Models;
using System.Configuration;

namespace BCMS.Controllers
{
    public class ReportController : Controller
    {
        private readonly double DEFAULT_DEPT_BUDGET = Convert.ToDouble(ConfigurationManager.AppSettings["DefaultDepartmentBudget"]);
        private readonly double DEFAULT_TOTAL_BUDGET = Convert.ToDouble(ConfigurationManager.AppSettings["DefaultTotalBudget"]);
        private readonly DateTime START_OF_THIS_MONTH = DateTime.Today.AddDays(1 - DateTime.Today.Day);
        private BCMSContext db = new BCMSContext();
        private DBLogic DBL = new DBLogic();

        // GET: /Report/
        public ActionResult Index()
        {
            return View(db.Reports.Where(r => r.ConsultantName == User.Identity.Name).Where(r => r.SupervisorApproved == "Submitted").ToList());
        }

        // GET: /Report/Details/5
        //This provides an expense details view that allows an consultant to add more expenses
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            Session["ReportID"] = null;
            ViewBag.TotalReportCost = GetReportCost(id);
            return View(report);
        }

        // GET: /Report/Details/5
        //This provides an expense details view that does not allow the user to add more expenses
        public ActionResult DetailsOnly(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            Session["ReportID"] = null;
            ViewBag.TotalReportCost = GetReportCost(id);
            return View(report);
        }

        [Authorize(Roles = "Consultant")]
        // GET: /Report/Create
        public ActionResult Create()
        {          
            return View();
        }

        // POST: /Report/Create
        //This creates a report and posts the ID for the redirct 
        [Authorize(Roles = "Consultant")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReportPK,ReportName,ConsultantName,type,SupervisorName,SupervisorApproved,StaffApproval,DateOfApproval")] Report report)
        {
            if (ModelState.IsValid)
            {
                DBL.AddReport(report, User.Identity.Name.ToString());
                return RedirectToAction("Details", new { id = report.ReportPK });
            }
            return View(report);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        // GET /REPORT/ConsultantSubmissions
        //This provides a list of user identified consultant submissions that have been submitted (a complete history)
        [Authorize(Roles="Consultant")]
        public ActionResult ConsultantSubmissions()
        {
            return View(db.Reports.Where(r => r.ConsultantName == User.Identity.Name).ToList());
        }
        // GET  /REPORT/ConsultantApprovals
        //This provides a list of user identified consultant submissions that have been approved
        [Authorize(Roles = "Consultant")]
        public ActionResult ConsultantApprovals()
        {
            return View(db.Reports.Where(r => r.ConsultantName == User.Identity.Name).Where(r => r.StaffApproval == "Approved").ToList());
        }

        //GET /REPORT/ConsulantAwaiting 
        //This provides a list of user identified consultant submissions that are pending to be reviewed
        [Authorize(Roles = "Consultant")]
        public ActionResult ConsultantAwaiting()
        {
            return View(db.Reports.Where(r => r.ConsultantName == User.Identity.Name && ( r.StaffApproval == null && r.SupervisorApproved != "Rejected")).ToList());
        }
        //GET /REPORT/SupervisorReports 
        //Provides a list of reports based on a user's department for reports that have been submitted for approval
        [Authorize(Roles = "Supervisor")]
        public ActionResult SupervisorReports()
        {
            DepartmentType dept = DeptCheck();

            return View(db.Reports.Where(r => r.type == dept).Where(r => r.SupervisorApproved == "Submitted").ToList());         
        }
        //GET /REPORT/SupervisorRejects
        //Provides a list of reports based on a user's department that have been rejected by Staff Accounts
        [Authorize(Roles = "Supervisor")]
        public ActionResult SupervisorRejects()
        {
            DepartmentType dept = DeptCheck();

            return View(db.Reports.Where(r => r.type == dept).Where(r => r.StaffApproval == "Rejected").ToList());
        }
        //GET /REPORT/SupervisorBudgets 
        //Provides the budget of a selected department
        [Authorize(Roles = "Supervisor")]
        public ActionResult SupervisorBudget()
        {
            DepartmentType dept = DeptCheck();
            double totalCurrency = 0;
            // this double loop goes through all the reports with that department
            // then gets the amount out.
            foreach (var report in (db.Reports.Where(x => x.type == dept).Where(x => x.SupervisorApproved == "Approved" && x.StaffApproval != "Rejected").Where(x => x.DateOfApproval >= START_OF_THIS_MONTH || x.DateOfApproval == null)))
            {
                foreach(var expense in report.Expenses)
                {                    
                    totalCurrency = expense.ConvertedAmount + totalCurrency;
                }             
            }  
            //ship it off to the view
            ViewBag.CurrentDepartment = dept;
            ViewBag.TotalExpenses = totalCurrency;
            ViewBag.RemainingBudget = (DEFAULT_DEPT_BUDGET - totalCurrency);
            return View();
        }
        // This is a re-useable method for dept checking
        private DepartmentType DeptCheck()
        {
            DepartmentType dept = DepartmentType.HigherEducation;
            if (User.IsInRole("HigherEducation"))
            {
                dept = DepartmentType.HigherEducation;
            }
            else if (User.IsInRole("Logistics"))
            {
                dept = DepartmentType.Logistics;
            }
            else if (User.IsInRole("State"))
            {
                dept = DepartmentType.State;
            }
            return dept;
        }
        //GET /REPORT/StaffBudget
        //This displays the staff budget for all departments based on the start of the month
        [Authorize(Roles = "Staff")]
        public ActionResult StaffBudget()
        {
            SupervisorList list = new SupervisorList();
            double totalCurrency = 0;
            double supervisorCurrency = 0;
            // goes through reports and gets the total amount of converted and adds it to the list to display on the view page
            foreach (var report in (db.Reports.Where(x => x.StaffApproval == "Approved").Where(x => x.DateOfApproval >= START_OF_THIS_MONTH)))
            {
                foreach (var expense in report.Expenses)
                {
                    totalCurrency += expense.ConvertedAmount;
                    supervisorCurrency += expense.ConvertedAmount;
                }
                list.AddToList(report.SupervisorName, supervisorCurrency);
                supervisorCurrency = 0;
            }
            ViewBag.SpentCompanyBudget = totalCurrency;
            ViewBag.RemainingCompanyBudget = DEFAULT_TOTAL_BUDGET - totalCurrency;
            // returns a custom object of a list with 2 columns simple stuff
            return View((object)list.ReturnSupervisors());
        }
        //GET /REPORT/StaffReports
        //This provides a list of reports that are awaiting staff approval
        [Authorize(Roles = "Staff")]
        public ActionResult StaffReports()
        {
            ViewBag.HigherBudgetRemaining = (DEFAULT_DEPT_BUDGET - GetSpentBudgetForStaff(DepartmentType.HigherEducation));
            ViewBag.StateBudgetRemaining = (DEFAULT_DEPT_BUDGET - GetSpentBudgetForStaff(DepartmentType.State));
            ViewBag.LogisticsBudgetRemaining = (DEFAULT_DEPT_BUDGET - GetSpentBudgetForStaff(DepartmentType.Logistics));

            return View(db.Reports.Where(r => r.StaffApproval == null).Where(r => r.SupervisorApproved == "Approved").ToList());
        }
        //GET /REPORT/Approve/id(5 etc)
        // this allows a report to be approved for supervisors 
        [Authorize(Roles = "Supervisor")]
        [HttpGet]
        public ActionResult Approve(int? id)
        {
            // if it's over budget it sends to a confirmation page to be super approved(pun intended)
            if (GetReportCost(id) <= (DEFAULT_DEPT_BUDGET - GetSpentBudgetForSupervisor()))
            {
                return RedirectToAction("ApproveCon", new {reportID = id});
            }
            else
            {
                Report report = db.Reports.Find(id);
                ViewBag.TotalForReport = GetReportCost(id);
                ViewBag.TotalBudgetRemaining = (DEFAULT_DEPT_BUDGET - GetSpentBudgetForSupervisor());
                return View(report);
            }
        }
        //A method for getting report cost of particular ID - no real logic 
        private double GetReportCost(int? reportID)
        {
            double amount = 0;

BCMS/BCMS/Views/Report/Approve.cshtml
@model BlueConsultingManagementSystem.Models.Report

@{
    ViewBag.Title = "Confirm Your Approval";
}
<h2>Details</h2>
<div>
    <h4>Report: @Model.ReportName</h4>

    @if (Model.Expenses != null && Model.Expenses.Count() > 0)
    {
        <table class="table">
            <tr>
                <th>
                    Description
                </th>
                <th>
                    Location
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Currency
                </th>
                <th>
                    Date of Expense
                </th>
                <th>
                    PDF Receipt
                </th>
                </tr>
            @*Displays all the expenses from one report on this page  *@
            @foreach (var exp in Model.Expenses)
            {
                <tr>
                    <td>
                        @exp.Description
                    </td>
                    <td>
                        @exp.Location
                    </td>
                    <td>
                        @exp.Amount
                    </td>
                    <td>
                        @exp.CType
                    </td>
                    <td>
                        @exp.DateOfExpense
                    </td>
                    <td>
                        @if (exp.PDFFile != null)
                        {
                            @Html.ActionLink("PDF", "PDFView", "Expense", new { id = exp.ExpensePK }, null)
                        }
                        else
                        {

                        }
                    </td>

                </tr>
            }
            <tr><td></td><td></td><td></td><td>Total Amount : $AUD @ViewBag.TotalForReport</td><td></td><td></td></tr>
        </table>
    }
    @* if this will force the budget to be negative this will appear  *@
    <h2> Are you sure you wish to confirm this report?</h2>
    <p> This report is over the @Model.type.ToString() remaining budget of $AUD @ViewBag.TotalBudgetRemaining.</p>
    <p> This report is worth $AUD @ViewBag.TotalForReport and would be over budget</p>

    <div class="btn btn-info">
        @Html.ActionLink("Confirm approval", "ApproveCon", "Report", new { ReportID = Model.ReportPK }, new { @style = "color:#000000;" })
        </div>
    <div class="btn btn-danger">
        @Html.ActionLink("Reject Report", "Reject", "Report", new { id = Model.ReportPK }, new { @style = "color:#000000;" })
        </div>
    <p>@Html.ActionLink("Back to reports list", "SupervisorReports", "Report")</p>  
    </div>

BCMS/BCMS/Views/Report/ConsultantApprovals.cshtml
@model IEnumerable<BlueConsultingManagementSystem.Models.Report>

@{
    ViewBag.Title = "Your APproved Reports";
}

<h2>Your Approved Reports</h2>

<table class="table">
    <tr>
        <th>
            Report Name
        </th>
        <th>
            Department
        </th>
        <th>
            Date of Approval
        </th>
    </tr>
    @* just iterates through all the items *@
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.ReportName, "DetailsOnly", new { id = item.ReportPK })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfApproval)
        </td>
    </tr>
}

</table>

BCMS/BCMS/Views/Report/ConsultantAwaiting.cshtml
@model IEnumerable<BlueConsultingManagementSystem.Models.Report>

@{
    ViewBag.Title = "Your Awaiting Reports";
}

<h2>Your Awaiting Reports</h2>

<table class="table">
    <tr>
        <th>
            Report Name
        </th>
        <th>
            Department
        </th>
        <th>
            Supervisor Approval Status
        </th>
        <th>
            Staff Approval Status
        </th>
    </tr>
    @* iterates through the model items   *@
@foreach (var item in Model) {
    <tr>
        <td>
           @Html.ActionLink(item.ReportName, "DetailsOnly", new { id = item.ReportPK })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SupervisorApproved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StaffApproval)
        </td>
    </tr>
}

</table>

BCMS/BCMS/Views/Report/ConsultantSubmissions.cshtml
@model IEnumerable<BlueConsultingManagementSystem.Models.Report>

@{
    ViewBag.Title = "Your Submitted Reports";
}

<h2>Your Submitted Reports</h2>

<table class="table">
    <tr>
        <th>
            Report Name
        </th>
        <th>
           Department
        </th>
        <th>
            Supervisor Approval Status
        </th>
        <th>
            Staff Approval Status
        </th>
        <th>
            Date of Approval
        </th>
    </tr>
    @* iterates through the model items   *@
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.ReportName, "DetailsOnly", new { id = item.ReportPK })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SupervisorApproved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StaffApproval)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfApproval)
        </td>
    </tr>
}

</table>

BCMS/BCMS/Views/Report/Create.cshtml
@model BlueConsultingManagementSystem.Models.Report

@{
    ViewBag.Title = "Create a New Report";
}

<h2>Create a New Report</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ReportName,"Report Name:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReportName)
                @Html.ValidationMessageFor(model => model.ReportName)
            </div>
        </div>

        <div class="form-group">
    @Html.LabelFor(model => model.type, "Department Type:" ,new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.DropDownListFor(model => model.type, new[]{
           new SelectListItem {Text = "Higher Education", Value = "HigherEducation"},
           new SelectListItem {Text = "Logistics", Value = "Logistics"},
           new SelectListItem {Text = "State", Value = "State"}})
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BCMS/BCMS/Views/Report/Details.cshtml
@model BlueConsultingManagementSystem.Models.Report

@{
    ViewBag.Title = "Report Expense Details";
}

<h2>Report Expense Details</h2>

<div>
    <h4>Report: @Model.ReportName</h4>
	
    @if(Model.Expenses !=null && Model.Expenses.Count() > 0)
    {
        <table class="table">
    <tr>
        <th>
            Description
        </th>
        <th>
            Location
        </th>
        <th>
            Amount
        </th>
        <th>
            Currency
        </th>
        <th>
            Date of Expense
        </th>
        <th>
            PDF Receipt
        </th>
            </tr>
            @* displays all the expenses in the report nothing crazy going on here *@
            @foreach (var exp in Model.Expenses)
            {
                <tr>
                    <td>
                        @exp.Description
                    </td>
                    <td>
                        @exp.Location
                    </td>
                    <td>
                        @exp.Amount
                    </td>
                    <td>
                        @exp.CType
                    </td>
                    <td>
                        @exp.DateOfExpense
                    </td>
                    <td>
                    @if (exp.PDFFile != null)
                    {
                        @Html.ActionLink("PDF", "PDFView", "Expense", new {id = exp.ExpensePK}, null)
                    }
                    else
                    {
                        
                    }
                    </td>
                </tr>
            }
            <tr><td></td><td></td><td></td><td>Total Amount : $AUD @ViewBag.TotalReportCost</td><td></td><td></td></tr>
            </table>
        @* This is split into three user options 
            supervisor - approve or reject
            staff - Approve or reject 
            consultant - can just add more expenses *@
        if (User.IsInRole("Supervisor"))
        {
           
            <div class="btn btn-info">
                @Html.ActionLink("Approve Report", "Approve", "Report", new { id = Model.ReportPK }, new { @style = "color:#000000;" })
            </div>
            <div class="btn btn-danger">
                @Html.ActionLink("Reject Report", "Reject", "Report", new { id = Model.ReportPK }, new { @style = "color:#000000;" })
            </div>
            <p>@Html.ActionLink("Back to reports list", "SupervisorReports", "Report")</p>  
        }
         else if (User.IsInRole("Staff"))
         {
             <div class="btn btn-info">
             @Html.ActionLink("Approve Report", "StaffApproval", "Report", new { id = Model.ReportPK }, new { @style = "color:#000000;" })
             </div>
            <div class="btn btn-danger">
                @Html.ActionLink("Reject Report", "StaffReject", "Report", new { id = Model.ReportPK }, new { @style = "color:#000000;" })
            </div>
            <p>@Html.ActionLink("Back to reports list", "StaffReports", "Report")</p>  
         }
    }
    else if (User.IsInRole("Staff") || User.IsInRole("Supervisor"))
    {
        @: No expenses to approve
    }

    @if(User.IsInRole("Consultant")){
    @Html.ActionLink("Add Expense", "Create", "Expense", new {ReportId = Model.ReportPK}, null)
    }
    
</div>

BCMS/BCMS/Views/Report/DetailsOnly.cshtml
@model BlueConsultingManagementSystem.Models.Report

@{
    ViewBag.Title = "Report Expense Details";
}

<h2>Report Expense Details</h2>
<div>
    <h4>Report: @Model.ReportName</h4>

    @if (Model.Expenses != null && Model.Expenses.Count() > 0)
    {
        <table class="table">
            <tr>
                <th>
                    Description
                </th>
                <th>
                    Location
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Currency
                </th>
                <th>
                    Date of Expense
                </th>
                <th>
                    PDF Receipt
                </th>
            </tr>
            @* just displaying the expenses *@
            @foreach (var exp in Model.Expenses)
            {
                <tr>
                    <td>
                        @exp.Description
                    </td>
                    <td>
                        @exp.Location
                    </td>
                    <td>
                        @exp.Amount
                    </td>
                    <td>
                        @exp.CType
                    </td>
                    <td>
                        @exp.DateOfExpense
                    </td>
                    <td>
                        @if (exp.PDFFile != null)
                        {
                            @Html.ActionLink("PDF", "PDFView", "Expense", new { id = exp.ExpensePK }, null)
                        }
                        else
                        {

                        }
                    </td>
                </tr>
            }
            <tr><td></td><td></td><td></td><td>Total Amount : $AUD @ViewBag.TotalReportCost</td><td></td><td></td></tr>
        </table>
    }
    @* more so for just displaying . *@
    else if (User.IsInRole("Staff") || User.IsInRole("Supervisor"))
    {
        @: No expenses to approve
    }

</div>
<p>
    @Html.ActionLink("Back to Home", "Index", "Home")
</p>

BCMS/BCMS/Views/Report/Index.cshtml
@model IEnumerable<BlueConsultingManagementSystem.Models.Report>

@{
    ViewBag.Title = "In Progress Reports";
}

<h2>In Progress Reports</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Report Name
        </th>
        <th>
            Department Type
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.ReportName, "Details", new { id=item.ReportPK })
            
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type)
        </td>
        
    </tr>
}

</table>

BCMS/BCMS/Views/Report/StaffApproval.cshtml
@model BlueConsultingManagementSystem.Models.Report
@*this is the confirmation page for checking if you want to approve above budgets.  *@
@{
    ViewBag.Title = "Confirm Your Approval";
}

<h2>Details</h2>
<div>
    <h4>Report: @Model.ReportName</h4>

    @if (Model.Expenses != null && Model.Expenses.Count() > 0)
    {
        <table class="table">
            <tr>
                <th>
                    Description
                </th>
                <th>
                    Location
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Currency
                </th>
                <th>
                    Date of Expense
                </th>
                <th>
                    PDF Receipt
                </th>
            </tr>
            @foreach (var exp in Model.Expenses)
            {
                <tr>
                    <td>
                        @exp.Description
                    </td>
                    <td>
                        @exp.Location
                    </td>
                    <td>
                        @exp.Amount
                    </td>
                    <td>
                        @exp.CType
                    </td>
                    <td>
                        @exp.DateOfExpense
                    </td>
                    <td>
                        @if (exp.PDFFile != null)
                        {
                            @Html.ActionLink("PDF", "PDFView", "Expense", new { id = exp.ExpensePK }, null)
                        }
                        else
                        {

                        }
                    </td>

                </tr>
            }
            <tr><td></td><td></td><td></td><td>Total Amount : $AUD @ViewBag.TotalForReport</td><td></td><td></td></tr>
        </table>
    }
            <h2> Are you sure you wish to confirm this report?</h2>
            <p> This report is over the @Model.type.ToString() remaining budget of $AUD @ViewBag.TotalBudgetRemaining. </p>
            <p> This report is worth $AUD @ViewBag.TotalForReport and would be over budget</p>

    <div class="btn btn-info">
        @* staff only options  *@
        @Html.ActionLink("Confirm Approval", "StaffApprovalCon", "Report", new { id = Model.ReportPK }, new { @style="color:#000000;"})
        </div>
    <div class="btn btn-danger">
        @Html.ActionLink("Reject Report", "StaffReject", "Report", new { id = Model.ReportPK }, new { @style="color:#000000;"})
        </div>
    <p>@Html.ActionLink("Back to reports list", "StaffReports", "Report")</p>  
    </div>

BCMS/BCMS/Views/Report/SupervisorBudget.cshtml
@model string

@{
    ViewBag.Title = "Your Current Department Budget";
}
@* the supervisors department budget  *@

<h2>Your Current Department Budget</h2>

<p>The total expenses for your department is: $AUD @ViewBag.TotalExpenses</p>
<p>The remaining budget for your department is: $AUD @ViewBag.RemainingBudget</p>